# Small original/bundle compatibility projects.
CASES = [
    ("baseline_flat_from_import", {"main.py": "from helper import value\nprint(value)", "helper.py": "value = 42"}),
    ("module_object", {"main.py": "import helper\nprint(helper.value)", "helper.py": "value = 42"}),
    ("module_alias", {"main.py": "import helper as h\nprint(h.value)", "helper.py": "value = 42"}),
    ("symbol_alias", {"main.py": "from helper import value as renamed\nprint(renamed)", "helper.py": "value = 42"}),
    ("relative_dot", {"main.py": "from pkg.run import value\nprint(value)", "pkg/__init__.py": "", "pkg/run.py": "from . import helper\nvalue = helper.value", "pkg/helper.py": "value = 42"}),
    ("relative_named", {"main.py": "from pkg.run import value\nprint(value)", "pkg/__init__.py": "", "pkg/run.py": "from .helper import value", "pkg/helper.py": "value = 42"}),
    ("package_false_self_cycle", {"main.py": "from pkg import value\nprint(value)", "pkg/__init__.py": "from pkg.helper import value", "pkg/helper.py": "value = 42"}),
    ("nested_dependency_order", {"main.py": "from pkg.consumer import result\nprint(result)", "pkg/__init__.py": "", "pkg/consumer.py": "from pkg.provider import VALUE\nresult = VALUE", "pkg/provider.py": "from pkg.base import BASE\nVALUE = BASE + 2", "pkg/base.py": "BASE = 40"}),
    ("namespace_package", {"main.py": "from pkg import helper\nprint(helper.value)", "pkg/helper.py": "value = 42"}),
    ("namespace_globals_collision", {"main.py": "from b import read\nprint(read())", "a.py": "VALUE = 'A'\ndef read():\n    return VALUE", "b.py": "from a import read\nVALUE = 'B'"}),
    ("dependency_main_guard", {"main.py": "from helper import value\nprint(value)", "helper.py": "value = 42\nif __name__ == '__main__':\n    print('UNEXPECTED HELPER CLI')"}),
    ("unrelated_side_effect", {"main.py": "print(42)", "unused.py": "raise RuntimeError('unused module executed')"}),
    ("unrelated_syntax_error", {"main.py": "print(42)", "unused.py": "def broken(:\n    pass"}),
    ("future_import_position", {"main.py": "from __future__ import annotations\nfrom helper import value\nprint(value)", "helper.py": "value = 42"}),
    ("empty_function_after_removal", {"main.py": "def load():\n    from helper import value\nload()\nprint(42)", "helper.py": "value = 42"}),
    ("lazy_import_becomes_eager", {"main.py": "def unused():\n    import helper\n    pass\nprint(42)", "helper.py": "raise RuntimeError('lazy module executed')"}),
    ("valid_lazy_cycle_rejected", {"main.py": "from a import f\nprint(f())", "a.py": "def f():\n    from b import value\n    return value", "b.py": "from a import f\nvalue = 42"}),
    ("conditional_import_becomes_eager", {"main.py": "if False:\n    import helper\n    pass\nprint(42)", "helper.py": "raise RuntimeError('disabled module executed')"}),
    ("dynamic_import", {"main.py": "import importlib\nm = importlib.import_module('helper')\nprint(m.value)", "helper.py": "value = 42"}),
    ("data_file", {"main.py": "from pathlib import Path\nprint(Path(__file__).with_name('data.txt').read_text())", "data.txt": "42"}),
    ("source_encoding", {"main.py": "from helper import value\nprint(value)", "helper.py": b"# coding: latin-1\nvalue = 'caf\xe9'\n"}),
    ("module_metadata", {"main.py": "from helper import name\nprint(name)", "helper.py": "name = __name__"}),
    ("missing_import_silently_removed", {"main.py": "from helper import missing\nprint(42)", "helper.py": "value = 42"}),
]
